apiVersion: v1
kind: Service
metadata:
  name:  $PROJECT_NAME
  labels:
    app: $PROJECT_NAME
##spec for Service
spec: 
  selector:
    app: $PROJECT_NAME
  ##accepts external requests by assinging the service an external ip adress
  ports:
    - protocol: TCP
      port : 80 
      #to wich pod it should forward the 
      targetPort: 80

